name = "angels-host-api3"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[[services]]
binding = "AUTO_DELIVERY"
service = "pharaoh-auto-delivery"

[[services]]
binding = "HALL_EL"
service = "angels-hosts-api3"
